### ISSUE TITLE
CSS [hidden] attribute selector conflicts with bootstrap v4 [hidden] rule

### ISSUE THREAD

**Issue by westurner** [django-debug-toolbar/django-debug-toolbar#850]
This bootstrap rule causes these elements (``div#djDebug, div#djDebugToolbar, div#djDebugToolbarHandle``) to not be displayed:

From https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css :
```css
template,
[hidden] {
  display: none;
}
```
